kind: pipeline
name: ABS LINUX

steps:
- name: Linux Kernel Build
  image: whynothugo/makepkg
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
  commands:
    - "export GITHUB_TOKEN"
    - sudo pacman -Sy base-devel bc kmod libelf pahole xmlto python-sphinx python-sphinx_rtd_theme graphviz imagemagick git github-cli bc pahole llvm curl zip wget --noconfirm
    - cd /home/notroot
    - git clone https://github.com/theradcolor/arch-build-system_linux && cd arch-build-system_linux
    - bash makepkg --syncdeps --skipinteg --skipinteg
    - bash post_build